server:
  port: 8782

spring:
  application:
    name: service-feign

eureka:
  instance:
    # 租约续租间隔时间
    lease-renewal-interval-in-seconds: 5
    # 租约到期持续时间
    lease-expiration-duration-in-seconds: 15
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    # 到注册中心获取最新信息的间隔时间，eureka本地缓存的刷新间隔时间
    registry-fetch-interval-seconds: 5

