server:
  port: 8782
spring:
  profiles:
    active: after_route

# 在application.yml建一个配置文件after_route，语法是三个横线
---
spring:
  # 此配置文件中通过spring.profiles来配置文件名，和spring.profiles.active一致
  profiles: after_route
  cloud:
    gateway:
      routes:
      - id: after_route
        uri: http://httpbin.org:80/
        predicates:
        - After=2017-01-20T17:42:47.789-07:00[America/Denver]
