server:
  port: 8081

eureka:
  instance:
    hostname: eureka-server-example
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/